[book]
authors = ["mklag", "spfeifer"]
language = "en"
multilingual = false
src = "src"
title = "HALion 7.1.30"
text-direction = "ltr"

[build]
build-dir = "book"
create-missing = true
use-default-preprocessors = true

[preprocessor]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "[[_TOC_]]"
max-level = 3

[output.html]
no-section-label = true
default-theme = "steinberg-light"
preferred-dark-theme = "steinberg-dark"

[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter

[output.linkcheck]
optional = true
exclude = ['.+\.(vstpreset|mid)']

[output.html.fold]
enable = true
level = 0
